package com.nexvary.aviationnavigator

internal val TR_STRINGS = listOf(
    "Ana Sayfa",
    "Harita",
    "Plan",
    "Radar",
    "Trafik",
    "Hakkında",
    "Geri",
    "Yenile",
    "Canlı hava trafiğine bağlanılıyor…",
    "%d uçak · ADSB.lol · Kahire FIR",
    "Canlı trafik kullanılamıyor: %s",
    "Havacılık çalışma alanı",
    "Canlı trafik, harita, radar ve uçuş planlama tek mobil çalışma alanında.",
    "İzlenen",
    "Havada",
    "Yerde",
    "Canlı öne çıkanlar",
    "En yüksek: %s · %d ft",
    "En hızlı: %s · %d kt",
    "Hızlı erişim",
    "Canlı harita",
    "MapLibre + canlı ADS-B uçakları",
    "Uçuş planı",
    "ICAO rota taslağı oluştur ve doğrula",
    "250 NM durumsal trafik görünümü",
    "Çağrı kodu, irtifa ve hızı incele",
    "Şirket, sürüm ve sosyal bağlantılar",
    "Aç",
    "Canlı hava sahası",
    "Yarıçap %d NM",
    "İzlenen %d",
    "Canlı ADS-B uçakları MapLibre üzerinde gösteriliyor",
    "Uçuş planlayıcı",
    "Temel bir ICAO rota taslağı oluşturun. Navigasyon verileri, prosedürler ve performans katmanları daha sonra bu motora eklenebilir.",
    "Kalkış ICAO",
    "Varış ICAO",
    "Seyir irtifası ft",
    "Rota / Hava yolları",
    "Planı doğrula",
    "Plan geçerli",
    "Plan durumu",
    "Rota taslağını doğrulamaya hazır",
    "Sonraki navigasyon katmanı",
    "Havalimanı/pist veritabanı, waypoint, VOR/NDB ve hava yolları",
    "Prosedürler",
    "SID / STAR / yaklaşma seçimi",
    "Performans",
    "Uçak profili, yakıt, süre, TOC/TOD ve dikey profil",
    "Canlı radar · %d NM",
    "Altın: havada · Gümüş: yerde · %d canlı iz",
    "Canlı trafik",
    "Canlı iz yüklenmedi",
    "NEXVARY Aviation Navigator Hakkında",
    "Sürüm %s",
    "NEXVARY Aviation Navigator canlı uçak farkındalığı, harita, radar ve uçuş planlama araçlarını tek Android çalışma alanında birleştirir.",
    "Yalnızca bilgi, planlama ve simülasyon amaçlıdır. Birincil navigasyon, ATC ayırma veya çarpışma önleme için sertifikalı değildir.",
    "Bağlantılarımız",
    "Web sitesi",
    "Facebook",
    "E-posta",
    "YouTube",
    "X",
    "Desteklenen diller",
    "%d ft",
    "%d kt",
    "Kalkış 4 harfli bir ICAO kodu olmalıdır",
    "Varış 4 harfli bir ICAO kodu olmalıdır",
    "Kalkış ve varış farklı olmalıdır",
    "Seyir irtifası 1.000 ile 60.000 ft arasında olmalıdır"
)

internal val ES_STRINGS = listOf(
    "Inicio",
    "Mapa",
    "Plan",
    "Radar",
    "Tráfico",
    "Acerca de",
    "Atrás",
    "Actualizar",
    "Conectando al tráfico aéreo en vivo…",
    "%d aeronaves · ADSB.lol · FIR de El Cairo",
    "Tráfico en vivo no disponible: %s",
    "Espacio de trabajo de aviación",
    "Tráfico en vivo, mapa, radar y planificación de vuelo en un solo espacio móvil.",
    "Seguidas",
    "En vuelo",
    "En tierra",
    "Datos destacados en vivo",
    "Más alta: %s · %d ft",
    "Más rápida: %s · %d kt",
    "Acceso rápido",
    "Mapa en vivo",
    "MapLibre + aeronaves ADS-B en vivo",
    "Plan de vuelo",
    "Crear y validar un borrador de ruta ICAO",
    "Vista situacional de tráfico de 250 NM",
    "Ver indicativo, altitud y velocidad",
    "Empresa, versión y enlaces sociales",
    "Abrir",
    "Espacio aéreo en vivo",
    "Radio %d NM",
    "Seguidas %d",
    "Aeronaves ADS-B en vivo mostradas en MapLibre",
    "Planificador de vuelo",
    "Cree un borrador básico de ruta ICAO. Los datos de navegación, procedimientos y rendimiento pueden añadirse después.",
    "ICAO de salida",
    "ICAO de destino",
    "Altitud de crucero ft",
    "Ruta / Aerovías",
    "Validar plan",
    "Plan válido",
    "Estado del plan",
    "Listo para validar el borrador de ruta",
    "Siguiente capa de navegación",
    "Base de aeropuertos/pistas, waypoints, VOR/NDB y aerovías",
    "Procedimientos",
    "Selección SID / STAR / aproximación",
    "Rendimiento",
    "Perfil de aeronave, combustible, tiempo, TOC/TOD y perfil vertical",
    "Radar en vivo · %d NM",
    "Dorado: en vuelo · Plata: en tierra · %d trazas en vivo",
    "Tráfico en vivo",
    "No hay trazas en vivo cargadas",
    "Acerca de NEXVARY Aviation Navigator",
    "Versión %s",
    "NEXVARY Aviation Navigator reúne seguimiento de aeronaves en vivo, mapa, radar y herramientas de planificación de vuelo en un único espacio Android.",
    "Solo para información, planificación y simulación. No está certificado para navegación primaria, separación ATC ni prevención de colisiones.",
    "Nuestros enlaces",
    "Sitio web",
    "Facebook",
    "Correo",
    "YouTube",
    "X",
    "Idiomas compatibles",
    "%d ft",
    "%d kt",
    "La salida debe ser un código ICAO de 4 letras",
    "El destino debe ser un código ICAO de 4 letras",
    "La salida y el destino deben ser diferentes",
    "La altitud de crucero debe estar entre 1.000 y 60.000 ft"
)
