package com.nexvary.aviationnavigator

internal val DE_STRINGS = listOf(
    "Start",
    "Karte",
    "Plan",
    "Radar",
    "Verkehr",
    "Über uns",
    "Zurück",
    "Aktualisieren",
    "Verbindung zum Live-Luftverkehr…",
    "%d Flugzeuge · ADSB.lol · Kairo FIR",
    "Live-Verkehr nicht verfügbar: %s",
    "Luftfahrt-Arbeitsbereich",
    "Live-Verkehr, Karte, Radar und Flugplanung in einem mobilen Arbeitsbereich.",
    "Verfolgt",
    "In der Luft",
    "Am Boden",
    "Live-Höhepunkte",
    "Höchstes: %s · %d ft",
    "Schnellstes: %s · %d kt",
    "Schnellzugriff",
    "Live-Karte",
    "MapLibre + Live-ADS-B-Flugzeuge",
    "Flugplan",
    "ICAO-Routenentwurf erstellen und prüfen",
    "250-NM-Verkehrslage",
    "Rufzeichen, Höhe und Geschwindigkeit prüfen",
    "Unternehmen, Version und Social-Links",
    "Öffnen",
    "Live-Luftraum",
    "Radius %d NM",
    "Verfolgt %d",
    "Live-ADS-B-Flugzeuge auf MapLibre dargestellt",
    "Flugplaner",
    "Erstellen Sie einen grundlegenden ICAO-Routenentwurf. Navigationsdaten, Verfahren und Leistungsdaten können später ergänzt werden.",
    "Abflug-ICAO",
    "Ziel-ICAO",
    "Reiseflughöhe ft",
    "Route / Luftstraßen",
    "Plan prüfen",
    "Plan gültig",
    "Planstatus",
    "Bereit zur Prüfung des Routenentwurfs",
    "Nächste Navigationsschicht",
    "Flughafen-/Pistendatenbank, Wegpunkte, VOR/NDB und Luftstraßen",
    "Verfahren",
    "SID / STAR / Anflugauswahl",
    "Leistung",
    "Flugzeugprofil, Treibstoff, Zeit, TOC/TOD und Vertikalprofil",
    "Live-Radar · %d NM",
    "Gold: in der Luft · Silber: am Boden · %d Live-Spuren",
    "Live-Verkehr",
    "Keine Live-Spuren geladen",
    "Über NEXVARY Aviation Navigator",
    "Version %s",
    "NEXVARY Aviation Navigator kombiniert Live-Flugzeuglage, Karte, Radar und Flugplanung in einem Android-Arbeitsbereich.",
    "Nur für Information, Planung und Simulation. Nicht für Primärnavigation, ATC-Staffelung oder Kollisionsvermeidung zertifiziert.",
    "Unsere Links",
    "Website",
    "Facebook",
    "E-Mail",
    "YouTube",
    "X",
    "Unterstützte Sprachen",
    "%d ft",
    "%d kt",
    "Der Abflug muss ein 4-stelliger ICAO-Code sein",
    "Das Ziel muss ein 4-stelliger ICAO-Code sein",
    "Abflug und Ziel müssen verschieden sein",
    "Die Reiseflughöhe muss zwischen 1.000 und 60.000 ft liegen"
)

internal val IT_STRINGS = listOf(
    "Home",
    "Mappa",
    "Piano",
    "Radar",
    "Traffico",
    "Info",
    "Indietro",
    "Aggiorna",
    "Connessione al traffico aereo in tempo reale…",
    "%d aeromobili · ADSB.lol · FIR Cairo",
    "Traffico live non disponibile: %s",
    "Spazio di lavoro aeronautico",
    "Traffico live, mappa, radar e pianificazione del volo in un unico spazio mobile.",
    "Tracciati",
    "In volo",
    "A terra",
    "Dati live in evidenza",
    "Più alto: %s · %d ft",
    "Più veloce: %s · %d kt",
    "Accesso rapido",
    "Mappa live",
    "MapLibre + aeromobili ADS-B live",
    "Piano di volo",
    "Crea e valida una bozza di rotta ICAO",
    "Vista situazionale del traffico a 250 NM",
    "Controlla nominativo, quota e velocità",
    "Azienda, versione e link social",
    "Apri",
    "Spazio aereo live",
    "Raggio %d NM",
    "Tracciati %d",
    "Aeromobili ADS-B live mostrati su MapLibre",
    "Pianificatore di volo",
    "Crea una bozza di rotta ICAO di base. Dati di navigazione, procedure e prestazioni potranno essere aggiunti in seguito.",
    "ICAO partenza",
    "ICAO destinazione",
    "Quota di crociera ft",
    "Rotta / Aerovie",
    "Valida piano",
    "Piano valido",
    "Stato piano",
    "Pronto a validare la bozza di rotta",
    "Prossimo livello di navigazione",
    "Database aeroporti/piste, waypoint, VOR/NDB e aerovie",
    "Procedure",
    "Selezione SID / STAR / avvicinamento",
    "Prestazioni",
    "Profilo aeromobile, carburante, tempo, TOC/TOD e profilo verticale",
    "Radar live · %d NM",
    "Oro: in volo · Argento: a terra · %d tracce live",
    "Traffico live",
    "Nessuna traccia live caricata",
    "Info su NEXVARY Aviation Navigator",
    "Versione %s",
    "NEXVARY Aviation Navigator unisce consapevolezza del traffico live, mappa, radar e strumenti di pianificazione del volo in un unico spazio Android.",
    "Solo per informazione, pianificazione e simulazione. Non certificato per navigazione primaria, separazione ATC o prevenzione collisioni.",
    "I nostri link",
    "Sito web",
    "Facebook",
    "Email",
    "YouTube",
    "X",
    "Lingue supportate",
    "%d ft",
    "%d kt",
    "La partenza deve essere un codice ICAO di 4 lettere",
    "La destinazione deve essere un codice ICAO di 4 lettere",
    "Partenza e destinazione devono essere diverse",
    "La quota di crociera deve essere tra 1.000 e 60.000 ft"
)
