package com.nexvary.aviationnavigator

internal val FR_STRINGS = listOf(
    "Accueil",
    "Carte",
    "Plan",
    "Radar",
    "Trafic",
    "À propos",
    "Retour",
    "Actualiser",
    "Connexion au trafic aérien en direct…",
    "%d aéronefs · ADSB.lol · FIR du Caire",
    "Trafic en direct indisponible : %s",
    "Espace de travail aéronautique",
    "Trafic en direct, carte, radar et planification de vol dans un seul espace mobile.",
    "Suivis",
    "En vol",
    "Au sol",
    "Points forts en direct",
    "Plus haut : %s · %d ft",
    "Plus rapide : %s · %d kt",
    "Accès rapide",
    "Carte en direct",
    "MapLibre + aéronefs ADS-B en direct",
    "Plan de vol",
    "Créer et valider un brouillon de route ICAO",
    "Vue situationnelle du trafic sur 250 NM",
    "Voir indicatif, altitude et vitesse",
    "Société, version et liens sociaux",
    "Ouvrir",
    "Espace aérien en direct",
    "Rayon %d NM",
    "Suivis %d",
    "Aéronefs ADS-B en direct affichés sur MapLibre",
    "Planificateur de vol",
    "Créez un brouillon de route ICAO de base. Les données de navigation, procédures et performances pourront être ajoutées ensuite.",
    "ICAO départ",
    "ICAO destination",
    "Altitude de croisière ft",
    "Route / Voies aériennes",
    "Valider le plan",
    "Plan valide",
    "État du plan",
    "Prêt à valider le brouillon de route",
    "Prochaine couche de navigation",
    "Base aéroports/pistes, waypoints, VOR/NDB et voies aériennes",
    "Procédures",
    "Sélection SID / STAR / approche",
    "Performances",
    "Profil avion, carburant, temps, TOC/TOD et profil vertical",
    "Radar en direct · %d NM",
    "Or : en vol · Argent : au sol · %d pistes en direct",
    "Trafic en direct",
    "Aucune piste en direct chargée",
    "À propos de NEXVARY Aviation Navigator",
    "Version %s",
    "NEXVARY Aviation Navigator réunit suivi des aéronefs en direct, carte, radar et outils de planification de vol dans un espace Android unique.",
    "Uniquement pour information, planification et simulation. Non certifié pour navigation primaire, séparation ATC ou évitement de collision.",
    "Nos liens",
    "Site web",
    "Facebook",
    "E-mail",
    "YouTube",
    "X",
    "Langues prises en charge",
    "%d ft",
    "%d kt",
    "Le départ doit être un code ICAO de 4 lettres",
    "La destination doit être un code ICAO de 4 lettres",
    "Le départ et la destination doivent être différents",
    "L’altitude de croisière doit être comprise entre 1 000 et 60 000 ft"
)

internal val UR_STRINGS = listOf(
    "ہوم",
    "نقشہ",
    "منصوبہ",
    "ریڈار",
    "ٹریفک",
    "ہمارے بارے میں",
    "واپس",
    "تازہ کریں",
    "براہِ راست فضائی ٹریفک سے رابطہ ہو رہا ہے…",
    "%d طیارے · ADSB.lol · قاہرہ FIR",
    "براہِ راست ٹریفک دستیاب نہیں: %s",
    "ہوابازی ورک اسپیس",
    "براہِ راست ٹریفک، نقشہ، ریڈار اور فلائٹ پلاننگ ایک موبائل ورک اسپیس میں۔",
    "ٹریک شدہ",
    "فضا میں",
    "زمین پر",
    "براہِ راست نمایاں معلومات",
    "سب سے بلند: %s · %d ft",
    "سب سے تیز: %s · %d kt",
    "فوری رسائی",
    "براہِ راست نقشہ",
    "MapLibre + براہِ راست ADS-B طیارے",
    "فلائٹ پلان",
    "ICAO روٹ ڈرافٹ بنائیں اور جانچیں",
    "250 NM ٹریفک صورتحال",
    "کال سائن، بلندی اور رفتار دیکھیں",
    "کمپنی، ورژن اور سوشل روابط",
    "کھولیں",
    "براہِ راست فضائی حدود",
    "رداس %d NM",
    "ٹریک شدہ %d",
    "براہِ راست ADS-B طیارے MapLibre پر دکھائے گئے ہیں",
    "فلائٹ پلانر",
    "بنیادی ICAO روٹ ڈرافٹ بنائیں۔ نیویگیشن ڈیٹا، طریقہ کار اور کارکردگی کی تہیں بعد میں شامل کی جا سکتی ہیں۔",
    "روانگی ICAO",
    "منزل ICAO",
    "کروز بلندی ft",
    "روٹ / ایئر ویز",
    "پلان جانچیں",
    "پلان درست ہے",
    "پلان کی حالت",
    "روٹ ڈرافٹ جانچنے کے لیے تیار",
    "اگلی نیویگیشن تہہ",
    "ایئرپورٹ/رن وے ڈیٹابیس، وے پوائنٹس، VOR/NDB اور ایئر ویز",
    "طریقہ کار",
    "SID / STAR / اپروچ انتخاب",
    "کارکردگی",
    "طیارہ پروفائل، ایندھن، وقت، TOC/TOD اور عمودی پروفائل",
    "براہِ راست ریڈار · %d NM",
    "سنہری: فضا میں · چاندی: زمین پر · %d براہِ راست ٹریک",
    "براہِ راست ٹریفک",
    "کوئی براہِ راست ٹریک لوڈ نہیں ہوا",
    "NEXVARY Aviation Navigator کے بارے میں",
    "ورژن %s",
    "NEXVARY Aviation Navigator براہِ راست طیارہ آگاہی، نقشہ، ریڈار اور فلائٹ پلاننگ ٹولز کو ایک Android ورک اسپیس میں جمع کرتا ہے۔",
    "صرف معلومات، منصوبہ بندی اور سمیولیشن کے لیے۔ بنیادی نیویگیشن، ATC علیحدگی یا تصادم سے بچاؤ کے لیے تصدیق شدہ نہیں۔",
    "ہمارے روابط",
    "ویب سائٹ",
    "فیس بک",
    "ای میل",
    "یوٹیوب",
    "X",
    "معاون زبانیں",
    "%d ft",
    "%d kt",
    "روانگی 4 حرفی ICAO کوڈ ہونا چاہیے",
    "منزل 4 حرفی ICAO کوڈ ہونا چاہیے",
    "روانگی اور منزل مختلف ہونی چاہئیں",
    "کروز بلندی 1,000 سے 60,000 ft کے درمیان ہونی چاہیے"
)
