package com.nexvary.aviationnavigator

internal val EN_STRINGS = listOf(
    "Home",
    "Map",
    "Plan",
    "Radar",
    "Traffic",
    "About",
    "Back",
    "Refresh",
    "Connecting to live traffic…",
    "%d aircraft · ADSB.lol · Cairo FIR",
    "Live traffic unavailable: %s",
    "Aviation workspace",
    "Live traffic, map, radar and flight planning in one mobile workspace.",
    "Tracked",
    "Airborne",
    "Ground",
    "Live highlights",
    "Highest: %s · %d ft",
    "Fastest: %s · %d kt",
    "Quick access",
    "Live map",
    "MapLibre + live ADS-B aircraft",
    "Flight plan",
    "Build and validate an ICAO route draft",
    "250 NM situational traffic scope",
    "Inspect callsign, altitude and speed",
    "Company, version and social links",
    "Open",
    "Live airspace",
    "Radius %d NM",
    "Tracked %d",
    "Live ADS-B aircraft plotted on MapLibre",
    "Flight planner",
    "Create a basic ICAO route draft. Navigation data, procedures and performance layers can plug into this engine next.",
    "Departure ICAO",
    "Destination ICAO",
    "Cruise altitude ft",
    "Route / Airways",
    "Validate plan",
    "Plan valid",
    "Plan status",
    "Ready to validate a route draft",
    "Next navigation layer",
    "Airport/runway database, waypoints, VOR/NDB and airways",
    "Procedures",
    "SID / STAR / approach selection",
    "Performance",
    "Aircraft profile, fuel, time, TOC/TOD and vertical profile",
    "Live radar · %d NM",
    "Gold: airborne · Silver: ground · %d live tracks",
    "Live traffic",
    "No live tracks loaded",
    "About NEXVARY Aviation Navigator",
    "Version %s",
    "NEXVARY Aviation Navigator combines live aircraft awareness, map, radar and flight-planning tools in one Android workspace.",
    "Informational, planning and simulation use only. Not certified for primary navigation, ATC separation or collision avoidance.",
    "Our links",
    "Website",
    "Facebook",
    "Email",
    "YouTube",
    "X",
    "Supported languages",
    "%d ft",
    "%d kt",
    "Departure must be a 4-letter ICAO code",
    "Destination must be a 4-letter ICAO code",
    "Departure and destination must be different",
    "Cruise altitude must be between 1,000 and 60,000 ft"
)
